### ISSUE TITLE
HDMI and Power LED dead after using this dtb file

### ISSUE THREAD

**Issue by jiejiecn** [mamin27/H616-mangopi#5]
After using this dtb file, the power LED is dead. Confused me a lot with the device status.  

And there's no signal on HDMI output.

**Comment by jiejiecn** [comment]
To be clear, the blue LED indicate for the system status is dead. Not the green LED.

**Comment by mamin27** [comment]
Hmm. I will check out of HDMI output signal. You are right about blue LED. If you have some advice let me know.

**Comment by jiejiecn** [comment]
According to the PCB design, PC13 is the STATUS_LED output.

In the dts file, I can only find the related section around line 483
![image](https://github.com/mamin27/H616-mangopi/assets/11746870/65637470-9667-4bfc-a22e-1962bc908de4)

Maybe you can try to remove those lines and have a try.

**Comment by mamin27** [comment]
Thanks, I will test it during weekend.

**Comment by mamin27** [comment]
Yes, LED (blue) is working now.
1. add OPi.GPIO library at the mangopi mq-quad (see package description part install OPi.GPIO lib)
2. run script led_mq_quad.py (flashing of LED)

**Comment by mamin27** [comment]
Here is how it works:

![flashing_blue_led](https://github.com/mamin27/H616-mangopi/assets/26118162/8856f48c-158e-4017-b81c-9196f279834b)

**Comment by mamin27** [comment]
**pin 77 (PC13): GPIO 300b000.pinctrl:77**  <-- LED PIN

```ps
root@mangopi:/sys/kernel/debug/pinctrl/300b000.pinctrl# cat pinmux-pins | grep PI
pin 74 (PC10): GPIO 300b000.pinctrl:74
pin 76 (PC12): GPIO 300b000.pinctrl:76
pin 77 (PC13): GPIO 300b000.pinctrl:77
pin 210 (PG18): GPIO 300b000.pinctrl:210
pin 256 (PI0): device 5097000.ahub-i2s0 function i2s0 group PI0
pin 257 (PI1): device 5097000.ahub-i2s0 function i2s0 group PI1
pin 258 (PI2): device 5097000.ahub-i2s0 function i2s0 group PI2
pin 259 (PI3): device 5097000.ahub-i2s0 function i2s0_din1 group PI3
pin 260 (PI4): device 5097000.ahub-i2s0 function i2s0_dout1 group PI4
pin 261 (PI5): UNCLAIMED
pin 262 (PI6): UNCLAIMED
pin 263 (PI7): device 5002400.i2c function i2c1 group PI7
pin 264 (PI8): device 5002400.i2c function i2c1 group PI8
pin 265 (PI9): device 5002800.i2c function i2c2 group PI9
pin 266 (PI10): device 5002800.i2c function i2c2 group PI10
pin 267 (PI11): UNCLAIMED
pin 268 (PI12): UNCLAIMED
pin 269 (PI13): UNCLAIMED
pin 270 (PI14): UNCLAIMED
pin 271 (PI15): UNCLAIMED
pin 272 (PI16): UNCLAIMED
```
